name: Terraform AutoFmt

on:
  push:
    branches: [main]

jobs:
  autofmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format (auto-fix)
        run: terraform fmt -recursive

      - name: Commit & Push if changed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "ci: terraform auto-format"
            git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "Nothing to commit."
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_demo_password: testpassword123
        run: terraform plan -lock=false
