name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -diff -recursive
      # Добавим комментарий с diff при ошибке форматирования
      - name: Fail if not formatted
        if: failure() && steps.fmt.outcome == 'failure'
        run: |
          echo "::error::Terraform files are not formatted. Please run 'terraform fmt' locally and push again."
          exit 1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_demo_password: testpassword123   # тестовый секрет для CI
        run: terraform plan -lock=false
